import Navigation from "@/components/ui/navigation";
import Footer from "@/components/sections/footer";

const TermsOfService = () => {
  return (
    <div className="min-h-screen">
      <Navigation />
      <div className="container mx-auto px-6 py-20 max-w-4xl">
        <div className="space-y-8">
          <div className="text-center space-y-4">
            <h1 className="text-display font-grotesk text-text-primary">Terms of Service</h1>
            <p className="text-body text-text-secondary">
              Last updated: {new Date().toLocaleDateString()}
            </p>
          </div>
          
          <div className="space-y-8 text-text-secondary">
            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Purpose</h2>
              <p>
                These Terms of Service ("Terms") govern your use of our platform and services related to private AI setup and consultation. By accessing or using our services, you agree to be bound by these Terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">License to Use the Platform</h2>
              <p>
                We grant you a limited, non-exclusive, non-transferable license to access and use our platform for its intended purpose. This license includes:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Access to our consultation services and guidance materials</li>
                <li>Use of AI-generated recommendations and setup instructions</li>
                <li>Access to educational content about private AI systems</li>
              </ul>
              <p>
                <strong>Important:</strong> While we provide guidance and recommendations, you retain full ownership of any AI systems we help you set up on your own hardware. We do not claim ownership of AI outputs generated by your private systems.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">AI Disclaimers</h2>
              <p>
                Our AI-powered guidance and recommendations are provided for informational purposes only and should not be considered as professional advice. Specifically:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>Medical Advice:</strong> Our services do not provide medical diagnosis or treatment recommendations</li>
                <li><strong>Legal Advice:</strong> We do not provide legal counsel or interpretation of laws and regulations</li>
                <li><strong>Technical Professional Services:</strong> Our guidance does not replace professional technical consultation for critical systems</li>
                <li><strong>Mechanical/Engineering Advice:</strong> We do not provide professional engineering or mechanical design services</li>
              </ul>
              <p>
                Always consult with qualified professionals for matters requiring specialized expertise. Our AI guidance is educational and should be verified by appropriate experts when implementing critical systems.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, we shall not be liable for any damages arising from:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Following AI-generated advice or recommendations</li>
                <li>Implementation of suggested AI systems or configurations</li>
                <li>Hardware failures, data loss, or system malfunctions</li>
                <li>Business interruption or loss of profits</li>
                <li>Indirect, incidental, special, or consequential damages</li>
              </ul>
              <p>
                Our total liability for any claims related to our services shall not exceed the amount you paid for our consultation services, if any.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">User Responsibilities</h2>
              <p>
                By using our services, you agree to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>No Hacking:</strong> Not attempt to gain unauthorized access to our systems or other users' data</li>
                <li><strong>No Scraping:</strong> Not use automated tools to extract content without permission</li>
                <li><strong>Appropriate Use:</strong> Use our services only for legitimate purposes related to private AI setup</li>
                <li><strong>Accurate Information:</strong> Provide truthful and accurate information when requesting consultations</li>
                <li><strong>Compliance:</strong> Follow all applicable laws and regulations in your jurisdiction</li>
                <li><strong>Security:</strong> Maintain the security of any credentials or access we provide</li>
              </ul>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Termination Rights</h2>
              <p>
                We reserve the right to suspend or terminate your access to our services at any time, with or without notice, for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Violation of these Terms of Service</li>
                <li>Misuse or abuse of our platform or services</li>
                <li>Attempted unauthorized access or security breaches</li>
                <li>Providing false or misleading information</li>
                <li>Any conduct that we determine is harmful to our business or other users</li>
              </ul>
              <p>
                Upon termination, your right to use our services will cease immediately. We may also remove any content you have posted to our platform.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Jurisdiction and Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the State of Tennessee, United States, without regard to conflict of law principles.
              </p>
              <p>
                Any legal action or proceeding arising under these Terms will be brought exclusively in the state or federal courts located in Tennessee, and you hereby consent to personal jurisdiction and venue therein.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Binding Arbitration</h2>
              <p>
                Any dispute, claim, or controversy arising out of or relating to these Terms or our services shall be settled by binding arbitration rather than in court, except that:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>You may pursue claims in small claims court if they qualify</li>
                <li>We may seek injunctive relief in court for intellectual property violations</li>
              </ul>
              <p>
                The arbitration will be conducted under the Commercial Arbitration Rules of the American Arbitration Association (AAA) and will take place in Tennessee. The arbitrator's decision shall be final and binding, and judgment may be entered in any court of competent jurisdiction.
              </p>
              <p>
                <strong>Class Action Waiver:</strong> You agree that any arbitration will be conducted on an individual basis and not as part of a class action or collective proceeding.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Changes to Terms</h2>
              <p>
                We may modify these Terms at any time by posting the revised terms on our website. Changes will be effective immediately upon posting unless otherwise specified. Your continued use of our services after changes are posted constitutes acceptance of the modified Terms.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Contact Information</h2>
              <p>
                If you have questions about these Terms of Service, please contact us:
              </p>
              <div className="bg-background-muted p-4 rounded-lg">
                <p>Email: barryharris82@icloud.com</p>
                <p>Subject line: Terms of Service Inquiry</p>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-xl font-semibold text-text-primary">Severability</h2>
              <p>
                If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect.
              </p>
            </section>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfService;