// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

const SUPABASE_URL = "https://zdzfaocsmtvmmecdefhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkemZhb2NzbXR2bW1lY2RlZmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzczMTIsImV4cCI6MjA2OTQxMzMxMn0.GT1X1vE8SRz_zfaoQ3ClUqOH3OnFFmhAToyelECsd1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});